name: docx_to_text
description: A small Dart package for converting docx files (Microsoft Word) to string.
version: 1.1.0
homepage: https://github.com/DayLight-Creative-Technologies/dlct-docx_to_text
repository: https://github.com/DayLight-Creative-Technologies/dlct-docx_to_text

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^4.0.0
  xml: ^6.5.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

